#!/bin/sh

case "$1" in
'start')
	service neo4j start
	;;
'stop')
	service neo4j stop
	;;
'restart')
	service neo4j restart
	;;
*)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;
esac
exit 0
